Blast4-request ::= {
  body queue-search {
    program "blastn",
    service "plain",
    queries bioseq-set {
      seq-set {
        seq {
          id {
            local str "Query_59520"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwToxo-Reg.Repetitiva"
                }
              }
            },
            title "FwToxo-Reg.Repetitiva"
          },
          inst {
            repr raw,
            mol na,
            length 18,
            seq-data ncbi2na '4482A120B0'H
          }
        },
        seq {
          id {
            local str "Query_59521"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">Probe-Reg.Repetitiva"
                }
              }
            },
            title "Probe-Reg.Repetitiva"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '525B7E8A22'H
          }
        },
        seq {
          id {
            local str "Query_59522"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvToxo-Reg.Repetitiva"
                }
              }
            },
            title "RvToxo-Reg.Repetitiva"
          },
          inst {
            repr raw,
            mol na,
            length 18,
            seq-data ncbi2na '87B2382980'H
          }
        },
        seq {
          id {
            local str "Query_59523"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwToxo-Regiao_Desconhecida"
                }
              }
            },
            title "FwToxo-Regiao_Desconhecida"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '2CE642D349'H
          }
        },
        seq {
          id {
            local str "Query_59524"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">Probe-Regiao_Desconhecida"
                }
              }
            },
            title "Probe-Regiao_Desconhecida"
          },
          inst {
            repr raw,
            mol na,
            length 21,
            seq-data ncbi2na '61C6D5E57F80'H
          }
        },
        seq {
          id {
            local str "Query_59525"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvToxo-Regiao_Desconhecida"
                }
              }
            },
            title "RvToxo-Regiao_Desconhecida"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '5C58D8B8D6'H
          }
        },
        seq {
          id {
            local str "Query_59526"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwEBV-BNRF1"
                }
              }
            },
            title "FwEBV-BNRF1"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi4na '44112284482382288842'H
          }
        },
        seq {
          id {
            local str "Query_59527"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">Probe-BNRF1"
                }
              }
            },
            title "Probe-BNRF1"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '1B93A16BC3'H
          }
        },
        seq {
          id {
            local str "Query_59528"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvEBV-BNRF1"
                }
              }
            },
            title "RvEBV-BNRF1"
          },
          inst {
            repr raw,
            mol na,
            length 23,
            seq-data ncbi2na '64A476C79D9C'H
          }
        },
        seq {
          id {
            local str "Query_59529"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwHIV_1-PolGeneRegion"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "FwHIV_1-PolGeneRegion"
          },
          inst {
            repr raw,
            mol dna,
            length 29,
            seq-data ncbi2na 'AC4B3CB285C45EC0'H
          }
        },
        seq {
          id {
            local str "Query_59530"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeHIV_1-PolGeneRegion"
                }
              }
            },
            title "ProbeHIV_1-PolGeneRegion"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '3CB5CF807B'H
          }
        },
        seq {
          id {
            local str "Query_59531"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvHIV_1-PolGeneRegion"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "RvHIV_1-PolGeneRegion"
          },
          inst {
            repr raw,
            mol dna,
            length 28,
            seq-data ncbi2na 'E8E9500BC043A5'H
          }
        },
        seq {
          id {
            local str "Query_59532"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwHBV-CoreProteinRegion"
                }
              }
            },
            title "FwHBV-CoreProteinRegion"
          },
          inst {
            repr raw,
            mol na,
            length 24,
            seq-data ncbi2na 'CA29ECA4C0FA'H
          }
        },
        seq {
          id {
            local str "Query_59533"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeHBV-CoreProteinRegion"
                }
              }
            },
            title "ProbeHBV-CoreProteinRegion"
          },
          inst {
            repr raw,
            mol na,
            length 19,
            seq-data ncbi2na '9127E8A7EC'H
          }
        },
        seq {
          id {
            local str "Query_59534"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvHBV-CoreProteinRegion"
                }
              }
            },
            title "RvHBV-CoreProteinRegion"
          },
          inst {
            repr raw,
            mol na,
            length 16,
            seq-data ncbi2na 'D177970D'H
          }
        },
        seq {
          id {
            local str "Query_59535"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwHCV-5linhaUTR"
                }
              }
            },
            title "FwHCV-5linhaUTR"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '1E5E32AE7E'H
          }
        },
        seq {
          id {
            local str "Query_59536"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeHCV-5linhaUTR"
                }
              }
            },
            title "ProbeHCV-5linhaUTR"
          },
          inst {
            repr raw,
            mol na,
            length 23,
            seq-data ncbi2na 'EBFF7F8AFCA0'H
          }
        },
        seq {
          id {
            local str "Query_59537"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvHCV-5linhaUTR"
                }
              }
            },
            title "RvHCV-5linhaUTR"
          },
          inst {
            repr raw,
            mol na,
            length 24,
            seq-data ncbi2na '2E55A8ADDB21'H
          }
        },
        seq {
          id {
            local str "Query_59538"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwT.pallidum_polA"
                }
              }
            },
            title "FwT.pallidum_polA"
          },
          inst {
            repr raw,
            mol na,
            length 21,
            seq-data ncbi2na '9E212632E000'H
          }
        },
        seq {
          id {
            local str "Query_59539"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeT.pallidum_polA"
                }
              }
            },
            title "ProbeT.pallidum_polA"
          },
          inst {
            repr raw,
            mol na,
            length 24,
            seq-data ncbi2na 'E8139EF89DD8'H
          }
        },
        seq {
          id {
            local str "Query_59540"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvT.pallidum_polA"
                }
              }
            },
            title "RvT.pallidum_polA"
          },
          inst {
            repr raw,
            mol na,
            length 22,
            seq-data ncbi2na '5748EACE70E0'H
          }
        },
        seq {
          id {
            local str "Query_59541"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwHSV1_2-UL30_DNApolimarase"
                }
              }
            },
            title "FwHSV1_2-UL30_DNApolimarase"
          },
          inst {
            repr raw,
            mol na,
            length 22,
            seq-data ncbi2na '5748EACE70E0'H
          }
        },
        seq {
          id {
            local str "Query_59542"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeHSV1_2-UL30_DNApolimarase"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "ProbeHSV1_2-UL30_DNApolimarase"
          },
          inst {
            repr raw,
            mol dna,
            length 26,
            seq-data ncbi2na '59607892115990'H
          }
        },
        seq {
          id {
            local str "Query_59543"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvHSV1_2-UL30_DNApolimarase"
                }
              }
            },
            title "RvHSV1_2-UL30_DNApolimarase"
          },
          inst {
            repr raw,
            mol na,
            length 22,
            seq-data ncbi2na 'C4504265E950'H
          }
        },
        seq {
          id {
            local str "Query_59544"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwCinomose_nucleocapsideo"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "FwCinomose_nucleocapsideo"
          },
          inst {
            repr raw,
            mol dna,
            length 27,
            seq-data ncbi2na '272FD37C1CD03C'H
          }
        },
        seq {
          id {
            local str "Query_59545"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeCinomose_nucleocapsideo"
                }
              }
            },
            title "ProbeCinomose_nucleocapsideo"
          },
          inst {
            repr raw,
            mol na,
            length 23,
            seq-data ncbi2na '938BFDE88BC0'H
          }
        },
        seq {
          id {
            local str "Query_59546"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvCinomose_nucleocapsideo"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "RvCinomose_nucleocapsideo"
          },
          inst {
            repr raw,
            mol dna,
            length 30,
            seq-data ncbi2na '93E01CECD69DFAB0'H
          }
        },
        seq {
          id {
            local str "Query_59547"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwLeish_inf_donov_DNAPolB"
                }
              }
            },
            title "FwLeish_inf_donov_DNAPolB"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na 'ED9F92148E'H
          }
        },
        seq {
          id {
            local str "Query_59548"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeLeish_inf_donov_DNAPolB"
                }
              }
            },
            title "ProbeLeish_inf_donov_DNAPolB"
          },
          inst {
            repr raw,
            mol na,
            length 19,
            seq-data ncbi2na 'B9D11798E4'H
          }
        },
        seq {
          id {
            local str "Query_59549"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvLeish_inf_donov_DNAPolB"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "RvLeish_inf_donov_DNAPolB"
          },
          inst {
            repr raw,
            mol dna,
            length 25,
            seq-data ncbi2na '49041F625E9140'H
          }
        },
        seq {
          id {
            local str "Query_59550"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwBabesia_18S"
                }
              }
            },
            title "FwBabesia_18S"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '2CE642D349'H
          }
        },
        seq {
          id {
            local str "Query_59551"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeBabesia_18S"
                }
              }
            },
            title "ProbeBabesia_18S"
          },
          inst {
            repr raw,
            mol na,
            length 21,
            seq-data ncbi2na '61C6D5E57F80'H
          }
        },
        seq {
          id {
            local str "Query_59552"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvBabesia_18S"
                }
              }
            },
            title "RvBabesia_18S"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '5C58D8B8D6'H
          }
        },
        seq {
          id {
            local str "Query_59553"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwFIV_GAG"
                }
              }
            },
            title "FwFIV_GAG"
          },
          inst {
            repr raw,
            mol na,
            length 24,
            seq-data ncbi4na '8A11522141114812AA814154'H
          }
        },
        seq {
          id {
            local str "Query_59554"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeFIV_GAG"
                }
              }
            },
            title "ProbeFIV_GAG"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi4na '44182155522148584888'H
          }
        },
        seq {
          id {
            local str "Query_59555"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvFIV_GAG"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "RvFIV_GAG"
          },
          inst {
            repr raw,
            mol dna,
            length 26,
            seq-data ncbi4na '84211A83884421415428288121'H
          }
        },
        seq {
          id {
            local str "Query_59556"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwFelv_U3_LTR"
                }
              }
            },
            title "FwFelv_U3_LTR"
          },
          inst {
            repr raw,
            mol na,
            length 15,
            seq-data ncbi2na '17A9569C'H
          }
        },
        seq {
          id {
            local str "Query_59557"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeFelv_U3_LTR"
                }
              }
            },
            title "ProbeFelv_U3_LTR"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi4na '14214114888211442252'H
          }
        },
        seq {
          id {
            local str "Query_59558"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvFelv_U3_LTR"
                }
              }
            },
            molinfo {
              biomol genomic
            },
            title "RvFelv_U3_LTR"
          },
          inst {
            repr raw,
            mol dna,
            length 26,
            seq-data ncbi4na '14422114512148811122224418'H
          }
        },
        seq {
          id {
            local str "Query_59559"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">FwAnaplasma_16S"
                }
              }
            },
            title "FwAnaplasma_16S"
          },
          inst {
            repr raw,
            mol na,
            length 18,
            seq-data ncbi2na '64BDA7A370'H
          }
        },
        seq {
          id {
            local str "Query_59560"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">ProbeAnaplasma_16S"
                }
              }
            },
            title "ProbeAnaplasma_16S"
          },
          inst {
            repr raw,
            mol na,
            length 23,
            seq-data ncbi2na 'E18494E49178'H
          }
        },
        seq {
          id {
            local str "Query_59561"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">RvAnaplasma_16S"
                }
              }
            },
            title "RvAnaplasma_16S"
          },
          inst {
            repr raw,
            mol na,
            length 20,
            seq-data ncbi2na '5413746118'H
          }
        }
      }
    },
    subject database "nt",
    algorithm-options {
      {
        name "EvalueThreshold",
        value cutoff e-value { 1, 10, 3 }
      },
      {
        name "UngappedMode",
        value boolean FALSE
      },
      {
        name "PercentIdentity",
        value real { 0, 10, 0 }
      },
      {
        name "HitlistSize",
        value integer 5000
      },
      {
        name "EffectiveSearchSpace",
        value big-integer 0
      },
      {
        name "DbLength",
        value big-integer 0
      },
      {
        name "WindowSize",
        value integer 0
      },
      {
        name "DustFiltering",
        value boolean FALSE
      },
      {
        name "RepeatFiltering",
        value boolean FALSE
      },
      {
        name "MaskAtHash",
        value boolean FALSE
      },
      {
        name "MismatchPenalty",
        value integer -3
      },
      {
        name "MatchReward",
        value integer 1
      },
      {
        name "GapOpeningCost",
        value integer 5
      },
      {
        name "GapExtensionCost",
        value integer 2
      },
      {
        name "StrandOption",
        value strand-type both-strands
      },
      {
        name "WordSize",
        value integer 7
      }
    },
    format-options {
      {
        name "Web_JobTitle",
        value string "42 sequences (ConferenciaDeEnsaios)"
      },
      {
        name "Web_NewWindow",
        value boolean TRUE
      },
      {
        name "Web_ShortQueryAdjust",
        value boolean TRUE
      }
    }
  }
}

