# Rosalind problem 1 - Counting DNA Nucleotides solved by 55670
# Enrico Giovanelli Tacconi Gimenez
#s = 'AACTAAAAGTCCACCAGCGAGATGAGTGACTCGTCAATCCGGGCGGGGCCATTACGATATGGGAGATAAACCGGCCATATTGAAGCCCCAATCGGGCAGAGTCTTGCACCAAACAACGGCCGAGATTTATTAGGATCCACTTAATGGCCGCTGAGGCCCCATTGCCTCAGATCCAGCACACCTAAATAGAGGGATCTTCATAAAAGTGTCTACACCGATAGTAATAGAACGTGAACTTCGTATTTTGCGACACCTAGGTTGTGGGGCCATTGTAGGGTCGGCACGGACTATATGTTGAGTAGGTGACAGCAGTAAGCCGGTGTTTGTGTGCTTGTTCGCCTGCCATCACCCGGGCGTGTGCACGGGAGGTCTTTATTAGCGCCGGAGCAACCTGAAGATTTGGCCATTTAACCCACCAGATTGAGGTCGGCCACTCGGAGTCTTCGAGGGACCTTGGAACAACGGGTTTGGAGCAGTCCTCCGATGAGCTTGGATTTAAGGGAGGTCGTTCGGACAGCTTAGCTCCCGCGTCGGCGACTTCAATTAGAAACAGGTGCCAGCGAATATCAAAGGAGCGATCGGAGAGAATGTAGAGTGTCGACCTAACCAGCCCGTCAGTCTCGTCTATGCCGGAGTAATTAGGGTTGTCAGACACAATCCGCGGGCATTACGCCGTGCGGATCGGGGCCTCGCTAAGGGGCGGCCAACCGTTAATTGGAAGAGCGTCGAGTCACGTTACCCGACGGGCAAAACGTTGTTGACGTGCCGTACGTGTGCTATGATCCCCTGCCACGTTGGCACCTACAGGAGGTA'

#print('Exercise 1:{} {} {} {} ' .format(s.count('A'), s.count('C'), s.count('G'), s.count('T')))
#DONE!
'''from Bio.Seq import Seq'''
# Rosalind problem 2 - Transcribing DNA into RNA solved by 49665

'''t = 'GTTTTCTGTAAAAACAAAATATCAATCCTGAGACTCACACGCACCGATATTCATCGGAGCGATTACGGGTAAGCGGTGCCATGCCTGCACCGAACCATGGGGTAACAATCCCGTGTTTCTATTGTTCCTGAAGGCCGGTATCGGGTTTATCGTGCACGGCATCCCCTTACTTGGACTGAATCCTAAACTCCCCGGTGTGAACACAGCCGCGGACGAGTAGTCCATGATGGACCCTACAGAGCTCAACAAGTAGCTGGCTTCGCCGGACCCTAAAGGTTCGGAACTGGGTGGAGTGCAGGGTAGTTTTAGGACCAGGCCTCCTTGCTGCTGGTCGTGCCCGCCCAAAGCCTACGCATGGAAATCAGGCCATAATATTATAAACGACGAGGGCTCATTTAGATTTCGTAGGGAAAGAATCAGGACCTACAATTTGGGCGGTAGTCAACTTTTACGCTCCCACAGTAGTAGTTTTCCAGGTTGTCCAGTGTGTCTTGGCGTGGGACCGCGATGTTGCGGTCGGCAAGGGGTCGGTAAGAGCTAGAGGTCTTAGATCCGTACTCATACTATCCACGCGAACCCCATTCGTCATCCACAAGCTGAACGTATGAGACTTTTTTACCCTTTACTTTCTCCCGTTGTAGAGTCTATAGCCTGGGACCGTCATCCGGACTGCCGGTCCCCGTAAGTTTGGGATTCAATTTTTTGCCTTGCTTTAGGCATAATTATCAGGCGGTGGCGGATTATTCTGTCTCATTGGGTGTGCCGCTGGTACGGACGGTATAGAACAAAATGCATTTTGAGCGGTCTTCCATGGATGTTGATGCTCTCGAAGTGACATGAATGCTTTTCCCTGAATACTCGGGGCCTCCACGAGGAAAAGGAAATCATCCTCGGAGAGAGGGCGAACCCACCACGCCGCTAGCGTTCCATTTGCCCGATTTAGTCTCACTTTCTGGCGTACAACCCAGAGTGGGTCGCTTCGTAAATATAAACCGCAACA'
trasncribe = t.replace('T',"U")

print(trasncribe)'''
# Rosalind problem 3 - Complementing a Strand of DNA solved by 45074
'''
s = Seq('AGAGTGCGCATGGTGGCGTCCCAAATGTACCTGTGTTCATGGCAGTACCTGACAGCCACTTATTATCTTGGCCTCAGCTCGCATGTCTATTAGTTTCACGCATTTGACCACTCCAGCCGTATTGGTATCCTTAGCCCATTTAACGGGATAAACCCTGGCGGTGGGGAGCCTCGGCATTTGATCAGCTTTGCGGCTGTCAGTGAGATCCGGGCCTATGACTTGGATCTTATCCTTGGGGCGGAGATATTAAAGGCCGAGTGCCGATCTCTGGAAGGTCGCATGATCGTTATGGTATACGACCGGAGTTTCCATCCCCATCGCATTAGCTTCCAGTGGCATGCAACGCCTTCCTCCGCCGCAGTCCTTAGGCCTCCCTAAGTTCTATGGATGCGGGACCATCGATCGTCCCACCTAAGCAAGCTAAAAGGAGAGCGGAGTAGCGTAATCTGTGTGTCGCAAGGAGGCACGACGAGGCGTCTTTCGCTATCTCCTTGATCAAGTAAATTCCTGGAGAACAATGGCCTCATGTCTGAGTCTGCCGAATCCCCGCTGGATCCAGTAAGATGACAGTCGCTCCTTTCATTCATATAAAACTGGGATAGGCAAGCAACCTGCAGAATTGACTACCATACATAGGGGGCCTCGGTTCGACTAACTTGCCCTCGCAGGTGGTTCGGACTATCGCTTGTGCTTGAGTCTGTGGCTTACACCAGCATTCATGTAGATAAATTACACAATGTCGTTTCACGCATTGGTTCACTTATGTGTAGTCGTGGGATGGTAGGCTCATACCCGGTGGAATGGCCCGTTGATCTGACTAATCA')
sr=s.reverse_complement()
print(sr)
'''

# Rosalind problem 4 - Rabbits and Recurrence Relations solved by 26195

# Fn = (Fn-1) + (Fn-2); F1 = F2 = 1
'''
n =29
k = 4
ultimo = 1
penultimo = 1

if (n==1) or (n==2):
    print(1)
else:
    count = 3
    while count <= n:
        termo = ultimo +(penultimo*k)
        penultimo = ultimo
        ultimo = termo
        count += 1
    print(termo)
    '''

# Rosalind problem 5 - Computing GC Content solved by 25990

'''from Bio import SeqIO
from Bio.SeqUtils import GC

path = str(input('Type path: '))
gc = []
with open(path,'r') as entrada:
    for rec in SeqIO.parse(entrada,'fasta'):
        gc.append(GC(rec.seq))
    max = (max(gc))
    index = gc.index(max)

with open(path,'r') as saida:
    for rec in SeqIO.parse(saida,'fasta'):
        if GC(rec.seq) == gc[index]:
            print(rec.id)
            print(gc[index])'''

# Rosalind problem 6 - Counting Point Mutations solved by 29392 (preciso entender esse código direito)
'''
s = 'AGAGTTGGAGGCGTTCGTCATTAGCATCAGGAACCCCGCCGTTCGTTTTGTCCATACGAAAGGTATGATAAATATTTCATCCCACATTTTGGGCTGGGCCCGACCCCCGAGGAGAGTAAAACTTCTTTCTAGCACCCGGCTGCCAGTCCCATACCGCGGTCCGTGGGATTAGGGTCTGTATTAATCGCTGCCGAGGTTTGCAGTGCTGTCCGTATCCGGCTATCCATACACAGTTGCACGGTTGTCCTGCCTGGCGAAAGATCTTGGTTAGTGCCTAGTTTCGTCAGGTTACGTGGGCCACCAAATGTTAGGGTAGCACGCCAAGAGAACACAGTCACTTCTTTGCCTCTTAATTAAGACAAGACGACACAAATAGCCTATCCACGCTAAGCTTTTCCTGTCCGGATATAGGAGAGCAGATAGACCCCAGTACAACACTGGGCACGTCTTACTCTCTCAAAGCCGAGTCGTTAGAATTCTACAACATACCATGAGCGCGCACCTCCCCTGAAAGCTGTTCTCTCATGATTATGATTATGTAAATAAGCTAGTGTGCCACGCGGGTCGTGGAAGAATCGTGTTCCGACTGTGTAGTAGTTCGCTGTACGCACTAACTAGGCGCGCGCAGCCTGAATACGTCACGTGAAGGTCGTGGAGTATCTGTCTGTTCCAGGGTATCGCCTTTCTCTGACTATTAGCCCGATGGCTTAAACGCGTCCCACTCTGGTGGAATGTACTTACCCAGATTTGTATCGTTCCGCACGGTCAACCAGCCATTGCGTAGCATTCACAATAGTCCGTTCGATTTACGCCCACTCAGCGGTTTTCCCGTGCAATTCGTATGGGTCACCGCTATTCACTGTACGGTAAATCAAAATCGTCTACGGTGGTACAGATTCGAAAAGATTCGTACGCAG'
t = 'CTATTTTCAGCCCCTTGTCCGTAGTAGGAGGTAACTACCAGATCGTTTTACGAAACCGACTGGGCAAATGAAGATTATTTACCTCATTCCAGAATGGCCCCGTAAATGTCGGAGATACACTCTTCTTTCGGACACACCCCTTCTAGACAAACATCGTCGGGAAAAGGAAAGGCGTGACTATAAATCCCCCCCTAGCCTGGCGTGCATGACCATCAGCGGCTCTCACTGGTCAGTTGCCCGTTGGTCATGCCACTCAAACGAACTTGGCTGGATATTAGGTGTACCCTGTTAATTCGCCCATCCAAAGTTGGCGGAGCACGCGACAGACCAACAAACACCTCTGCCAATCTTTGATTAGGCAATCCGAGAAAGATACCCCTAGGATGATGCCTATTATTCATCGGCAAATACTTGGACATACGGGCTCACGTACGGCAGTTAATAGGACCCAATGTCCCAATACCGACCCTCTAGAATTCTGTAACAGACGACGTGCACGCAACACCCGCGAGGCCTGCTCTCATCTGATTATGAATTAGGGTGGCTGTCTCACTCTTGCGGAATAAGTCGAGGCTACATGTCGCAACTTTGTAGTAGTTCCCTATGCGAACTAAGTTGATGGACCAATATACATTTCGTCACATGGCGAGGGTGTAGTACTTCTAGGGTCCAATGTAGGTCGTCTCTCGTACTGATTGCCGGTTGGCTCTAACCCTTACCAGGTGGGCGGCTAGTCGGCGGCTGGGTATCTATCGCTTTTCAGGTCTGTCCCGTCCTCGTGATTGCCTCTGAATTGCCAGCATCACCCTCTCTGGCCTGGCTAAGCTCTCGGGCGAGTAATACGAATCCCCGTTATGCACTGAAAGTAGAAGCGACGTCATCCATGGAAGCGACGATTTGAGGCCAGGAGTACGCAC'
Hdistante = sum(ch1 != ch2 for ch1, ch2 in zip(s,t))

print(Hdistante)'''

# Rosalind problem 7 Mendel's First Law solved by 17355

k = 2 #homozigoto dominante
m = 2 #heterozigoto
n = 2 #homozigoto recessivo

total = k + m + n

pk = k/total
pm = m/total
pn = n/total


homodom = #probabilidade de ser homozigoto dominante
heter = #probabilidade de ser heterozigoto

p = '?' # probabilidade que um atch de dois individuos resulte num individuo que possua um alelo dominante
